RoR Group Capstone - Recipe App
Enning94/RoR-Recipe-App-group-project pull request #65
Opened 2023-09-15 21:59 UTC by Enning94

### Recipe_App: Review
In this project, we:
- Followed the layout of the wireframes provided.
- Built login page and registration page with Devise.
- Created Food list:
   -  It displays a list of food and the quantity of food added by the logged-in user.
   - It leads to a form that allows users to add new food.
- Created Recipes list:
    - It displays a list of recipes created by the logged-in user.
    - It leads to recipe details.
    - If the user is the owner of the recipe, it allows the user to delete it.
- Created Public recipe list:
  - It displays a list of all public recipes ordered by the newest.
  - It leads to recipe details.
- Created Recipe details:
  - It displays a toggle button that allows for a recipe to be made public or private.
  - If the recipe is public or the user is the owner of the recipe, it displays the recipe details.
  - If the user is the owner of the recipe, it leads to the form that allows the user to add new food.
- Created General shopping list view :
  - It shows the list of food that is missing for all recipes of the logged-in user
  - It counts the total number of food items and the total price of the missing food.
- Created a navigation menu that allows users to open all of the pages we created.
- Wrote unit and integration tests

2023-09-15 22:30 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Enning94  and @Odongo006 , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media0.giphy.com/media/72RxB1QZqw9N1ueGAJ/giphy.gif"/> |

## Highlights

- [ ].. ✅ Green linters
- [ ].. ✅ App is working correctly
- [ ].. ✅ Great readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-15 22:30 UTC, joskalenda commented on spec/models/recipe_spec.rb
> +    recipe2 = Recipe.create(user_id: 1, name: 'Recipe 1', description: 'Recipe 1 description', cooking_time: 1,
- [ ] This line is causing the test to fail, as shown in the image below, I would appreciate you fix this issue, and kudos on your job, you did an amazing job
<img width="629" alt="1" src="https://github.com/Enning94/RoR-Recipe-App-group-project/assets/77843050/0a3df988-3ac3-43a7-95f2-1d7fa559faed">

2023-09-15 22:50 UTC, Enning94 commented on spec/models/recipe_spec.rb
> +    recipe2 = Recipe.create(user_id: 1, name: 'Recipe 1', description: 'Recipe 1 description', cooking_time: 1,
<img width="1072" alt="Screenshot 2023-09-15 at 10 43 13 PM" src="https://github.com/Enning94/RoR-Recipe-App-group-project/assets/79149176/f690fb29-764c-4d2e-affd-8d26b4157c6d">


### Attached is a screenshot showing all tests are passing locally, we will appreciate further description of what is causing the error in different environment and how we can fix that. Thank you

2023-09-16 11:19 UTC, joel-kalema approved these changes
Hi Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights
Tests are passing 👍 
![Screenshot 2023-09-16 131303](https://github.com/Enning94/RoR-Recipe-App-group-project/assets/57408419/0b800806-05be-40a2-b09c-c90788ce5267)

The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-16 11:19 UTC, joel-kalema commented on README.md
> +
- [ ] [OPTINAL] Please fix the LICENCE link to make your README more professional 👍 

![Screenshot 2023-09-16 123319](https://github.com/Enning94/RoR-Recipe-App-group-project/assets/57408419/5b5a8775-cfc5-403c-a516-0364f9d5afd6)

2023-09-16 11:50 UTC, Enning94 commented on README.md
> +
License fixed, thanks

2023-09-16 11:54 UTC, merged